const initialTasks = [
  {
    id: 'SNT-221',
    sourceSystem: 'SMMS',
    department: 'S&T',
    assetId: 'PM-4471',
    assetType: 'Point Machine',
    corridorId: 'C01',
    location: 'SRC Yard, Line 3',
    taskType: 'Point machine defect repair',
    criticality: 'Critical',
    defectSeverity: 92,
    overdueDays: 14,
    estimatedDuration: 90,
    requiredBlockType: 'Signalling Disconnection',
    crew: 'S&T Gang B',
    dueDate: '2026-08-26',
    scheduledDate: '2026-09-08',
    status: 'Open',
    priority: 94,
    priorityFactors: [
      { label: 'Critical criticality asset', contribution: 30, positive: true },
      { label: '14 days overdue', contribution: 29, positive: true },
      { label: 'High defect severity', contribution: 18, positive: true },
      { label: 'High-traffic corridor (C01)', contribution: 15, positive: true },
      { label: 'No blocking dependencies', contribution: 5, positive: true },
    ],
  },
  {
    id: 'ENG-104',
    sourceSystem: 'TMS',
    department: 'Engineering',
    assetId: 'TRK-1120',
    assetType: 'Track',
    corridorId: 'C01',
    location: 'HWH–SRC, KM 12/4',
    taskType: 'Rail fracture repair',
    criticality: 'Critical',
    defectSeverity: 88,
    overdueDays: 6,
    estimatedDuration: 60,
    requiredBlockType: 'Traffic Block',
    crew: 'PWay Gang 3',
    dueDate: '2026-09-03',
    scheduledDate: '2026-09-14',
    status: 'Open',
    priority: 85,
    priorityFactors: [
      { label: 'Critical criticality asset', contribution: 30, positive: true },
      { label: '6 days overdue', contribution: 20, positive: true },
      { label: 'High defect severity', contribution: 18, positive: true },
      { label: 'High-traffic corridor (C01)', contribution: 15, positive: true },
      { label: 'No blocking dependencies', contribution: 5, positive: true },
    ],
  },
  {
    id: 'SNT-087',
    sourceSystem: 'SMMS',
    department: 'S&T',
    assetId: 'SIG-2209',
    assetType: 'Signal',
    corridorId: 'C01',
    location: 'SRC Home Signal',
    taskType: 'Signal maintenance',
    criticality: 'High',
    defectSeverity: 64,
    overdueDays: 3,
    estimatedDuration: 45,
    requiredBlockType: 'Signalling Disconnection',
    crew: 'S&T Gang B',
    dueDate: '2026-09-06',
    scheduledDate: '2026-09-14',
    status: 'Open',
    priority: 72,
    priorityFactors: [
      { label: 'High criticality asset', contribution: 24, positive: true },
      { label: '3 days overdue', contribution: 15, positive: false },
      { label: 'High defect severity', contribution: 13, positive: true },
      { label: 'High-traffic corridor (C01)', contribution: 15, positive: true },
      { label: 'No blocking dependencies', contribution: 5, positive: true },
    ],
  },
  {
    id: 'TD-031',
    sourceSystem: 'TDMS',
    department: 'Traction',
    assetId: 'OHE-8802',
    assetType: 'OHE',
    corridorId: 'C02',
    location: 'BLS–CTC, KM 214',
    taskType: 'OHE inspection',
    criticality: 'Medium',
    defectSeverity: 41,
    overdueDays: 0,
    estimatedDuration: 60,
    requiredBlockType: 'Power Block',
    crew: 'TRD Team 1',
    dueDate: '2026-09-14',
    scheduledDate: '2026-09-15',
    status: 'Open',
    priority: 50,
    priorityFactors: [
      { label: 'Medium criticality asset', contribution: 17, positive: false },
      { label: 'Within due window', contribution: 12, positive: false },
      { label: 'Moderate defect severity', contribution: 8, positive: false },
      { label: 'High-traffic corridor (C02)', contribution: 15, positive: true },
      { label: 'No blocking dependencies', contribution: 5, positive: true },
    ],
  },
  {
    id: 'ENG-118',
    sourceSystem: 'TMS',
    department: 'Engineering',
    assetId: 'TRN-330',
    assetType: 'Turnout',
    corridorId: 'C02',
    location: 'CTC Yard, Turnout 14A',
    taskType: 'Turnout renewal',
    criticality: 'High',
    defectSeverity: 71,
    overdueDays: 9,
    estimatedDuration: 120,
    requiredBlockType: 'Traffic Block',
    crew: 'PWay Gang 5',
    dueDate: '2026-08-31',
    scheduledDate: '2026-09-12',
    status: 'Open',
    priority: 81,
    priorityFactors: [
      { label: 'High criticality asset', contribution: 24, positive: true },
      { label: '9 days overdue', contribution: 24, positive: true },
      { label: 'High defect severity', contribution: 14, positive: true },
      { label: 'High-traffic corridor (C02)', contribution: 15, positive: true },
      { label: 'No blocking dependencies', contribution: 5, positive: true },
    ],
  },
  {
    id: 'TD-055',
    sourceSystem: 'TDMS',
    department: 'Traction',
    assetId: 'TSS-12',
    assetType: 'Traction Substation',
    corridorId: 'C02',
    location: 'BBS TSS',
    taskType: 'Transformer oil filtration',
    criticality: 'High',
    defectSeverity: 68,
    overdueDays: 2,
    estimatedDuration: 180,
    requiredBlockType: 'Power Block',
    crew: 'TRD Team 2',
    dueDate: '2026-09-07',
    scheduledDate: '2026-09-07',
    status: 'Open',
    priority: 73,
    priorityFactors: [
      { label: 'High criticality asset', contribution: 24, positive: true },
      { label: 'Within due window', contribution: 14, positive: false },
      { label: 'High defect severity', contribution: 14, positive: true },
      { label: 'High-traffic corridor (C02)', contribution: 15, positive: true },
      { label: 'No blocking dependencies', contribution: 5, positive: true },
    ],
  },
  {
    id: 'ENG-142',
    sourceSystem: 'TMS',
    department: 'Engineering',
    assetId: 'BRG-77',
    assetType: 'Bridge',
    corridorId: 'C03',
    location: 'GII–TATA, Br. 412',
    taskType: 'Bridge girder inspection',
    criticality: 'Critical',
    defectSeverity: 79,
    overdueDays: 11,
    estimatedDuration: 150,
    requiredBlockType: 'Corridor Block',
    crew: 'Bridge Unit 1',
    dueDate: '2026-08-29',
    scheduledDate: '2026-09-15',
    status: 'Open',
    priority: 84,
    priorityFactors: [
      { label: 'Critical criticality asset', contribution: 30, positive: true },
      { label: '11 days overdue', contribution: 26, positive: true },
      { label: 'High defect severity', contribution: 16, positive: true },
      { label: 'Medium-traffic corridor (C03)', contribution: 10, positive: false },
      { label: 'No blocking dependencies', contribution: 5, positive: true },
    ],
  },
  {
    id: 'SNT-113',
    sourceSystem: 'SMMS',
    department: 'S&T',
    assetId: 'TC-5521',
    assetType: 'Track Circuit',
    corridorId: 'C02',
    location: 'KGP–BLS, TC-119',
    taskType: 'Track circuit failure',
    criticality: 'High',
    defectSeverity: 73,
    overdueDays: 5,
    estimatedDuration: 75,
    requiredBlockType: 'Signalling Disconnection',
    crew: 'S&T Gang A',
    dueDate: '2026-09-05',
    scheduledDate: '2026-09-05',
    status: 'Open',
    priority: 76,
    priorityFactors: [
      { label: 'High criticality asset', contribution: 24, positive: true },
      { label: '5 days overdue', contribution: 18, positive: true },
      { label: 'High defect severity', contribution: 15, positive: true },
      { label: 'High-traffic corridor (C02)', contribution: 15, positive: true },
      { label: 'No blocking dependencies', contribution: 5, positive: true },
    ],
  },
  {
    id: 'ENG-160',
    sourceSystem: 'TMS',
    department: 'Engineering',
    assetId: 'TRK-2044',
    assetType: 'Track',
    corridorId: 'C04',
    location: 'BBS–KUR, KM 8',
    taskType: 'Ballast cleaning',
    criticality: 'Medium',
    defectSeverity: 38,
    overdueDays: 0,
    estimatedDuration: 240,
    requiredBlockType: 'Traffic Block',
    crew: 'PWay Gang 7',
    dueDate: '2026-09-18',
    scheduledDate: '2026-09-18',
    status: 'Open',
    priority: 45,
    priorityFactors: [
      { label: 'Medium criticality asset', contribution: 17, positive: false },
      { label: 'Within due window', contribution: 12, positive: false },
      { label: 'Low defect severity', contribution: 8, positive: false },
      { label: 'Medium-traffic corridor (C04)', contribution: 10, positive: false },
      { label: 'No blocking dependencies', contribution: 5, positive: true },
    ],
  },
  {
    id: 'TD-072',
    sourceSystem: 'TDMS',
    department: 'Traction',
    assetId: 'OHE-9110',
    assetType: 'OHE',
    corridorId: 'C01',
    location: 'PKU–KGP, KM 96',
    taskType: 'OHE tension adjustment',
    criticality: 'Medium',
    defectSeverity: 46,
    overdueDays: 1,
    estimatedDuration: 90,
    requiredBlockType: 'Power Block',
    crew: 'TRD Team 1',
    dueDate: '2026-09-11',
    scheduledDate: '2026-09-11',
    status: 'Open',
    priority: 53,
    priorityFactors: [
      { label: 'Medium criticality asset', contribution: 17, positive: false },
      { label: 'Within due window', contribution: 13, positive: false },
      { label: 'Moderate defect severity', contribution: 9, positive: false },
      { label: 'High-traffic corridor (C01)', contribution: 15, positive: true },
      { label: 'No blocking dependencies', contribution: 5, positive: true },
    ],
  },
  {
    id: 'SNT-131',
    sourceSystem: 'SMMS',
    department: 'S&T',
    assetId: 'PM-4490',
    assetType: 'Point Machine',
    corridorId: 'C03',
    location: 'TATA Yard, Line 5',
    taskType: 'Point machine overhaul',
    criticality: 'Medium',
    defectSeverity: 52,
    overdueDays: 4,
    estimatedDuration: 120,
    requiredBlockType: 'Signalling Disconnection',
    crew: 'S&T Gang C',
    dueDate: '2026-09-08',
    scheduledDate: '2026-09-08',
    status: 'Open',
    priority: 56,
    priorityFactors: [
      { label: 'Medium criticality asset', contribution: 17, positive: false },
      { label: '4 days overdue', contribution: 16, positive: true },
      { label: 'Moderate defect severity', contribution: 10, positive: false },
      { label: 'Medium-traffic corridor (C03)', contribution: 10, positive: false },
      { label: 'No blocking dependencies', contribution: 5, positive: true },
    ],
  },
  {
    id: 'ENG-171',
    sourceSystem: 'TMS',
    department: 'Engineering',
    assetId: 'TRK-1180',
    assetType: 'Track',
    corridorId: 'C01',
    location: 'HWH–SRC, KM 4',
    taskType: 'Rail grinding',
    criticality: 'Low',
    defectSeverity: 22,
    overdueDays: 0,
    estimatedDuration: 180,
    requiredBlockType: 'Traffic Block',
    crew: 'PWay Gang 3',
    dueDate: '2026-09-22',
    scheduledDate: '2026-09-22',
    status: 'Open',
    priority: 35,
    priorityFactors: [
      { label: 'Low criticality asset', contribution: 8, positive: false },
      { label: 'Within due window', contribution: 12, positive: false },
      { label: 'Low defect severity', contribution: 4, positive: false },
      { label: 'High-traffic corridor (C01)', contribution: 15, positive: true },
      { label: 'No blocking dependencies', contribution: 5, positive: true },
    ],
  },
  {
    id: 'TD-088',
    sourceSystem: 'TDMS',
    department: 'Traction',
    assetId: 'OHE-8830',
    assetType: 'OHE',
    corridorId: 'C02',
    location: 'CTC–BBS, KM 240',
    taskType: 'Insulator replacement',
    criticality: 'High',
    defectSeverity: 66,
    overdueDays: 7,
    estimatedDuration: 60,
    requiredBlockType: 'Power Block',
    crew: 'TRD Team 2',
    dueDate: '2026-09-02',
    scheduledDate: '2026-09-02',
    status: 'Open',
    priority: 75,
    priorityFactors: [
      { label: 'High criticality asset', contribution: 24, positive: true },
      { label: '7 days overdue', contribution: 21, positive: true },
      { label: 'High defect severity', contribution: 13, positive: true },
      { label: 'High-traffic corridor (C02)', contribution: 15, positive: true },
      { label: 'No blocking dependencies', contribution: 5, positive: true },
    ],
  },
  {
    id: 'SNT-146',
    sourceSystem: 'SMMS',
    department: 'S&T',
    assetId: 'SIG-2240',
    assetType: 'Signal',
    corridorId: 'C04',
    location: 'KUR Distant Signal',
    taskType: 'Signal lamp replacement',
    criticality: 'Low',
    defectSeverity: 18,
    overdueDays: 0,
    estimatedDuration: 30,
    requiredBlockType: 'Signalling Disconnection',
    crew: 'S&T Gang D',
    dueDate: '2026-09-20',
    scheduledDate: '2026-09-20',
    status: 'Open',
    priority: 32,
    priorityFactors: [
      { label: 'Low criticality asset', contribution: 8, positive: false },
      { label: 'Within due window', contribution: 12, positive: false },
      { label: 'Low defect severity', contribution: 4, positive: false },
      { label: 'Medium-traffic corridor (C04)', contribution: 10, positive: false },
      { label: 'No blocking dependencies', contribution: 5, positive: true },
    ],
  },
  {
    id: 'ENG-188',
    sourceSystem: 'TMS',
    department: 'Engineering',
    assetId: 'LC-231',
    assetType: 'Level Crossing',
    corridorId: 'C05',
    location: 'SRC–ULT, LC-231',
    taskType: 'Level crossing resurfacing',
    criticality: 'Medium',
    defectSeverity: 44,
    overdueDays: 2,
    estimatedDuration: 120,
    requiredBlockType: 'Traffic Block',
    crew: 'PWay Gang 9',
    dueDate: '2026-09-09',
    scheduledDate: '2026-09-16',
    status: 'Open',
    priority: 52,
    priorityFactors: [
      { label: 'Medium criticality asset', contribution: 17, positive: false },
      { label: 'Within due window', contribution: 14, positive: false },
      { label: 'Moderate defect severity', contribution: 9, positive: false },
      { label: 'Medium-traffic corridor (C05)', contribution: 10, positive: false },
      { label: 'No blocking dependencies', contribution: 5, positive: true },
    ],
  },
  {
    id: 'TD-101',
    sourceSystem: 'TDMS',
    department: 'Traction',
    assetId: 'TSS-08',
    assetType: 'Traction Substation',
    corridorId: 'C01',
    location: 'KGP TSS',
    taskType: 'Circuit breaker maintenance',
    criticality: 'Critical',
    defectSeverity: 84,
    overdueDays: 8,
    estimatedDuration: 120,
    requiredBlockType: 'Power Block',
    crew: 'TRD Team 1',
    dueDate: '2026-08-30',
    scheduledDate: '2026-09-18',
    status: 'Open',
    priority: 86,
    priorityFactors: [
      { label: 'Critical criticality asset', contribution: 30, positive: true },
      { label: '8 days overdue', contribution: 23, positive: true },
      { label: 'High defect severity', contribution: 17, positive: true },
      { label: 'High-traffic corridor (C01)', contribution: 15, positive: true },
      { label: 'No blocking dependencies', contribution: 5, positive: true },
    ],
  },
  {
    id: 'SNT-159',
    sourceSystem: 'SMMS',
    department: 'S&T',
    assetId: 'TC-5540',
    assetType: 'Track Circuit',
    corridorId: 'C01',
    location: 'SRC–PKU, TC-140',
    taskType: 'Track circuit calibration',
    criticality: 'Medium',
    defectSeverity: 49,
    overdueDays: 0,
    estimatedDuration: 45,
    requiredBlockType: 'Signalling Disconnection',
    crew: 'S&T Gang A',
    dueDate: '2026-09-16',
    scheduledDate: '2026-09-16',
    status: 'Open',
    priority: 53,
    priorityFactors: [
      { label: 'Medium criticality asset', contribution: 17, positive: false },
      { label: 'Within due window', contribution: 12, positive: false },
      { label: 'Moderate defect severity', contribution: 10, positive: false },
      { label: 'High-traffic corridor (C01)', contribution: 15, positive: true },
      { label: 'No blocking dependencies', contribution: 5, positive: true },
    ],
  },
  {
    id: 'ENG-202',
    sourceSystem: 'TMS',
    department: 'Engineering',
    assetId: 'TRN-350',
    assetType: 'Turnout',
    corridorId: 'C03',
    location: 'GII Yard, Turnout 7',
    taskType: 'Turnout inspection',
    criticality: 'Medium',
    defectSeverity: 40,
    overdueDays: 3,
    estimatedDuration: 60,
    requiredBlockType: 'Traffic Block',
    crew: 'PWay Gang 5',
    dueDate: '2026-09-08',
    scheduledDate: '2026-09-08',
    status: 'Open',
    priority: 52,
    priorityFactors: [
      { label: 'Medium criticality asset', contribution: 17, positive: false },
      { label: '3 days overdue', contribution: 15, positive: false },
      { label: 'Moderate defect severity', contribution: 8, positive: false },
      { label: 'Medium-traffic corridor (C03)', contribution: 10, positive: false },
      { label: 'No blocking dependencies', contribution: 5, positive: true },
    ],
  },
  {
    id: 'ENG-221',
    sourceSystem: 'TMS',
    department: 'Engineering',
    assetId: 'BRG-81',
    assetType: 'Bridge',
    corridorId: 'C02',
    location: 'BLS–CTC, Br. 388',
    taskType: 'Bridge bearing replacement',
    criticality: 'Critical',
    defectSeverity: 90,
    overdueDays: 16,
    estimatedDuration: 300,
    requiredBlockType: 'Corridor Block',
    crew: 'Bridge Unit 2',
    dueDate: '2026-08-24',
    scheduledDate: '2026-09-14',
    status: 'Open',
    priority: 96,
    priorityFactors: [
      { label: 'Critical criticality asset', contribution: 30, positive: true },
      { label: '16 days overdue', contribution: 30, positive: true },
      { label: 'High defect severity', contribution: 18, positive: true },
      { label: 'High-traffic corridor (C02)', contribution: 15, positive: true },
      { label: 'No blocking dependencies', contribution: 5, positive: true },
    ],
  },
  {
    id: 'ENG-277',
    sourceSystem: 'TMS',
    department: 'Engineering',
    assetId: 'TRK-1250',
    assetType: 'Track',
    corridorId: 'C02',
    location: 'BLS–CTC, KM 220',
    taskType: 'Rail fracture repair',
    criticality: 'Critical',
    defectSeverity: 55,
    overdueDays: 0,
    estimatedDuration: 60,
    requiredBlockType: 'Traffic Block',
    crew: 'PWay Gang 7',
    dueDate: '2026-09-01',
    scheduledDate: '2026-09-01',
    status: 'Completed',
    priority: 55,
    priorityFactors: [
      { label: 'Critical criticality asset', contribution: 30, positive: true },
      { label: 'Within due window', contribution: 12, positive: false },
      { label: 'Moderate defect severity', contribution: 11, positive: false },
      { label: 'High-traffic corridor (C02)', contribution: 15, positive: true },
      { label: 'No blocking dependencies', contribution: 5, positive: true },
    ],
  },
  {
    id: 'ENG-286',
    sourceSystem: 'TMS',
    department: 'Engineering',
    assetId: 'BRG-92',
    assetType: 'Bridge',
    corridorId: 'C05',
    location: 'SRC–ULT, Br. 501',
    taskType: 'Bridge deck repair',
    criticality: 'High',
    defectSeverity: 64,
    overdueDays: 7,
    estimatedDuration: 240,
    requiredBlockType: 'Corridor Block',
    crew: 'Bridge Unit 1',
    dueDate: '2026-09-01',
    scheduledDate: '2026-09-16',
    status: 'Open',
    priority: 74,
    priorityFactors: [
      { label: 'High criticality asset', contribution: 24, positive: true },
      { label: '7 days overdue', contribution: 21, positive: true },
      { label: 'High defect severity', contribution: 13, positive: true },
      { label: 'Medium-traffic corridor (C05)', contribution: 10, positive: false },
      { label: 'No blocking dependencies', contribution: 5, positive: true },
    ],
  },
]

const initialRecommendedBlocks = [
  {
    id: 'REC-101',
    date: '2026-09-14',
    corridorId: 'C01',
    section: 'HWH–SRC',
    start: '11:30',
    end: '13:15',
    durationMin: 105,
    blockType: 'Traffic Block',
    confidence: 'High',
    utilization: 87.5,
    operationalImpact: 'Low',
    status: 'Recommended',
    taskIds: ['ENG-104', 'SNT-087'],
    criticalTasks: 1,
    downtimeSavedMin: 55,
    reasons: [
      '105 minutes of compatible Engineering + S&T work bundled into one block',
      '87.5% utilisation of the available 120-minute window',
      'Includes 1 critical rail-fracture repair (ENG-104)',
      'No timetable conflict — clears before 18045 East Coast Express at 13:15',
      'Avoids a separate signalling disconnection later in the week',
    ],
    alternative: {
      start: '15:00',
      end: '16:45',
      operationalImpact: 'High',
      note: 'Overlaps freight forecast window; higher operational risk',
    },
  },
  {
    id: 'REC-102',
    date: '2026-09-14',
    corridorId: 'C02',
    section: 'BLS–CTC',
    start: '12:00',
    end: '15:00',
    durationMin: 180,
    blockType: 'Corridor Block',
    confidence: 'High',
    utilization: 100,
    operationalImpact: 'Medium',
    status: 'Recommended',
    taskIds: ['ENG-221'],
    criticalTasks: 1,
    downtimeSavedMin: 40,
    reasons: [
      'Clears the most overdue critical task (ENG-221, 16 days overdue)',
      'Full 180-minute corridor block matches the bridge bearing replacement duration',
      'Scheduled between freight forecast and 12703 Falaknuma Express',
      'Bridge Unit 2 crew available and unconflicted',
    ],
    alternative: {
      start: '2026-09-17 09:00',
      end: '12:00',
      operationalImpact: 'Medium',
      note: 'Delays critical work by 3 days — not preferred',
    },
  },
  {
    id: 'REC-103',
    date: '2026-09-15',
    corridorId: 'C03',
    section: 'GII–TATA',
    start: '09:00',
    end: '11:30',
    durationMin: 150,
    blockType: 'Corridor Block',
    confidence: 'Medium',
    utilization: 100,
    operationalImpact: 'Low',
    status: 'Recommended',
    taskIds: ['ENG-142'],
    criticalTasks: 1,
    downtimeSavedMin: 30,
    reasons: [
      'Critical bridge girder inspection (ENG-142) within its 150-minute requirement',
      'Medium-traffic corridor with a clear morning window',
      'No passenger movement conflict in the block period',
    ],
    alternative: {
      start: '15:00',
      end: '17:30',
      operationalImpact: 'Medium',
      note: 'Available but reduces daylight inspection time',
    },
  },
  {
    id: 'REC-104',
    date: '2026-09-15',
    corridorId: 'C04',
    section: 'BBS–KUR',
    start: '14:00',
    end: '15:00',
    durationMin: 60,
    blockType: 'Power Block',
    confidence: 'High',
    utilization: 100,
    operationalImpact: 'Low',
    status: 'Recommended',
    taskIds: ['TD-031'],
    criticalTasks: 0,
    downtimeSavedMin: 20,
    reasons: [
      'OHE inspection (TD-031) fully fits the 60-minute power block',
      '100% utilisation with a single-department task',
      'Low-traffic afternoon window with no forecast freight',
    ],
  },
  {
    id: 'REC-105',
    date: '2026-09-16',
    corridorId: 'C05',
    section: 'SRC–ULT',
    start: '13:10',
    end: '16:00',
    durationMin: 170,
    blockType: 'Corridor Block',
    confidence: 'Medium',
    utilization: 92,
    operationalImpact: 'Low',
    status: 'Recommended',
    taskIds: ['ENG-286', 'ENG-188'],
    criticalTasks: 0,
    downtimeSavedMin: 35,
    reasons: [
      'Bundles bridge deck repair (ENG-286) with level-crossing resurfacing (ENG-188)',
      '92% utilisation of a 170-minute freight-corridor window',
      'Both tasks on compatible sections of C05',
      'Freight-only corridor — minimal passenger impact',
    ],
  },
]

const initialConflicts = [
  {
    id: 'CF-01',
    type: 'Operational',
    severity: 'Critical',
    title: 'Block overlaps scheduled passenger movement',
    description: 'Proposed block on C01 SRC–PKU (16:10–16:55) overlaps 22201 Duronto Express arriving 16:20.',
    corridorId: 'C01',
    affectedTasks: ['SNT-177'],
    affectedTrains: ['22201'],
    time: '16:10–16:55',
    suggestedAction: 'Shift block to 13:35–14:20 available window or reduce scope to fit before 16:20.',
    resolved: false,
  },
  {
    id: 'CF-02',
    type: 'Resource',
    severity: 'Warning',
    title: 'Same S&T crew assigned to overlapping tasks',
    description: 'S&T Gang B is assigned to SNT-221 (09:00–10:30) and SNT-087 (11:30–13:15) on the same day with insufficient transit buffer.',
    corridorId: 'C01',
    affectedTasks: ['SNT-221', 'SNT-087'],
    affectedTrains: [],
    time: '09:00 / 11:30',
    suggestedAction: 'Reassign SNT-087 to S&T Gang A or add a 45-minute transit buffer.',
    resolved: false,
  },
  {
    id: 'CF-03',
    type: 'Corridor',
    severity: 'Critical',
    title: 'Two incompatible activities request the same section',
    description: 'ENG-118 (Traffic Block) and TD-055 (Power Block) both request CTC Yard within the same window — incompatible block conditions.',
    corridorId: 'C02',
    affectedTasks: ['ENG-118', 'TD-055'],
    affectedTrains: [],
    time: '12:00–14:00',
    suggestedAction: 'Sequence the two blocks or move TD-055 to the next feasible power-block window.',
    resolved: false,
  },
  {
    id: 'CF-04',
    type: 'Capacity',
    severity: 'Warning',
    title: 'Requested work exceeds available window',
    description: 'Bundled request on C01 is 165 minutes but the available block window is only 120 minutes.',
    corridorId: 'C01',
    affectedTasks: ['ENG-104', 'SNT-087', 'SNT-193'],
    affectedTrains: [],
    time: '11:30–13:30',
    suggestedAction: 'Drop SNT-193 to a later window; bundle only ENG-104 + SNT-087 (105 min).',
    resolved: false,
  },
  {
    id: 'CF-05',
    type: 'Dependency',
    severity: 'Info',
    title: 'Task dependency not yet scheduled',
    description: 'ENG-233 depends on ENG-188 (level-crossing resurfacing), which is not scheduled before it.',
    corridorId: 'C05',
    affectedTasks: ['ENG-233', 'ENG-188'],
    affectedTrains: [],
    time: '—',
    suggestedAction: 'Schedule ENG-188 first, or bundle both into the C05 corridor block on 16 Sep.',
    resolved: false,
  },
  {
    id: 'CF-06',
    type: 'Operational',
    severity: 'Warning',
    title: 'Freight forecast reduces window confidence',
    description: 'Proposed C02 block partially overlaps GDS-5521 freight forecast (confidence 65%).',
    corridorId: 'C02',
    affectedTasks: ['TD-088'],
    affectedTrains: ['GDS-5521'],
    time: '11:00–11:45',
    suggestedAction: 'Start block at 12:00 to clear the freight forecast window.',
    resolved: true,
  },
  {
    id: 'CF-07',
    type: 'Operational',
    severity: 'Info',
    title: 'Block ends close to blackout period',
    description: 'C03 block ends 11:30, 2.5h before the 14:00 CRS inspection blackout — within buffer tolerance.',
    corridorId: 'C03',
    affectedTasks: ['ENG-142'],
    affectedTrains: [],
    time: '09:00–11:30',
    suggestedAction: 'No action required — buffer satisfied.',
    resolved: true,
  },
  {
    id: 'CF-08',
    type: 'Resource',
    severity: 'Warning',
    title: 'Bridge unit double-booked across corridors',
    description: 'Bridge Unit 1 is required for ENG-142 (C03) and ENG-286 (C05) on adjacent days with tight turnaround.',
    corridorId: 'C03',
    affectedTasks: ['ENG-142', 'ENG-286'],
    affectedTrains: [],
    time: '15 Sep / 16 Sep',
    suggestedAction: 'Confirm crew transit feasibility or assign Bridge Unit 2 to ENG-286.',
    resolved: false,
  },
]

module.exports = {
  initialTasks,
  initialRecommendedBlocks,
  initialConflicts,
}
