/**
 * Centralized Role-Based Access Control (RBAC) Configuration for Rail-Sanket
 * Defines granular permissions and assigns them strictly to roles.
 */

const PERMISSIONS = {
  // User & Administrative Management
  USERS_MANAGE: 'USERS_MANAGE',
  AUDIT_VIEW: 'AUDIT_VIEW',

  // Data Visibility
  DATA_VIEW_ALL: 'DATA_VIEW_ALL',

  // Task Operations
  TASKS_CREATE: 'TASKS_CREATE',
  TASKS_UPDATE: 'TASKS_UPDATE',
  TASKS_STATUS_UPDATE: 'TASKS_STATUS_UPDATE',

  // Block Planning & Approvals
  BLOCKS_CREATE: 'BLOCKS_CREATE',
  BLOCKS_SUBMIT_REVIEW: 'BLOCKS_SUBMIT_REVIEW',
  BLOCKS_APPROVE: 'BLOCKS_APPROVE',
  BLOCKS_REJECT: 'BLOCKS_REJECT',

  // Operational Conflict Management
  CONFLICTS_RESOLVE: 'CONFLICTS_RESOLVE',

  // Simulation & Optimization Engines
  SIMULATION_RUN: 'SIMULATION_RUN',
  OPTIMIZATION_RUN: 'OPTIMIZATION_RUN',
  OPTIMIZATION_APPLY: 'OPTIMIZATION_APPLY',

  // Operational Requisitions & Management Reporting
  REPORTS_GENERATE: 'REPORTS_GENERATE',

  // Operational Alert Intelligence & Action Center
  ALERTS_VIEW: 'ALERTS_VIEW',
  ALERTS_ACKNOWLEDGE: 'ALERTS_ACKNOWLEDGE',
  ALERTS_REVIEW: 'ALERTS_REVIEW',
  ALERTS_RESOLVE: 'ALERTS_RESOLVE',
  ALERTS_DISMISS: 'ALERTS_DISMISS',
  ALERTS_EVALUATE: 'ALERTS_EVALUATE',
}

const ROLE_PERMISSIONS = {
  ADMIN: [
    PERMISSIONS.USERS_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.DATA_VIEW_ALL,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.TASKS_STATUS_UPDATE,
    PERMISSIONS.BLOCKS_CREATE,
    PERMISSIONS.BLOCKS_SUBMIT_REVIEW,
    PERMISSIONS.BLOCKS_APPROVE,
    PERMISSIONS.BLOCKS_REJECT,
    PERMISSIONS.CONFLICTS_RESOLVE,
    PERMISSIONS.SIMULATION_RUN,
    PERMISSIONS.OPTIMIZATION_RUN,
    PERMISSIONS.OPTIMIZATION_APPLY,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.ALERTS_VIEW,
    PERMISSIONS.ALERTS_ACKNOWLEDGE,
    PERMISSIONS.ALERTS_REVIEW,
    PERMISSIONS.ALERTS_RESOLVE,
    PERMISSIONS.ALERTS_DISMISS,
    PERMISSIONS.ALERTS_EVALUATE,
  ],

  CONTROLLER: [
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.DATA_VIEW_ALL,
    PERMISSIONS.BLOCKS_SUBMIT_REVIEW,
    PERMISSIONS.BLOCKS_APPROVE,
    PERMISSIONS.BLOCKS_REJECT,
    PERMISSIONS.CONFLICTS_RESOLVE,
    PERMISSIONS.SIMULATION_RUN,
    PERMISSIONS.OPTIMIZATION_RUN,
    PERMISSIONS.OPTIMIZATION_APPLY,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.TASKS_STATUS_UPDATE,
    PERMISSIONS.ALERTS_VIEW,
    PERMISSIONS.ALERTS_ACKNOWLEDGE,
    PERMISSIONS.ALERTS_REVIEW,
    PERMISSIONS.ALERTS_RESOLVE,
    PERMISSIONS.ALERTS_DISMISS,
    PERMISSIONS.ALERTS_EVALUATE,
  ],

  PLANNER: [
    PERMISSIONS.DATA_VIEW_ALL,
    PERMISSIONS.TASKS_CREATE,
    PERMISSIONS.TASKS_UPDATE,
    PERMISSIONS.TASKS_STATUS_UPDATE,
    PERMISSIONS.BLOCKS_CREATE,
    PERMISSIONS.BLOCKS_SUBMIT_REVIEW,
    PERMISSIONS.SIMULATION_RUN,
    PERMISSIONS.OPTIMIZATION_RUN,
    PERMISSIONS.OPTIMIZATION_APPLY,
    PERMISSIONS.REPORTS_GENERATE,
    PERMISSIONS.ALERTS_VIEW,
    PERMISSIONS.ALERTS_ACKNOWLEDGE,
    PERMISSIONS.ALERTS_REVIEW,
    PERMISSIONS.ALERTS_EVALUATE,
    // Note: Cannot approve final blocks directly, cannot manage users
  ],

  MAINTENANCE_OFFICER: [
    PERMISSIONS.DATA_VIEW_ALL,
    PERMISSIONS.TASKS_STATUS_UPDATE,
    PERMISSIONS.SIMULATION_RUN,
    PERMISSIONS.ALERTS_VIEW,
    PERMISSIONS.ALERTS_ACKNOWLEDGE,
    PERMISSIONS.ALERTS_EVALUATE,
    // Note: Cannot create or approve blocks, cannot resolve railway traffic conflicts
  ],

  VIEWER: [
    PERMISSIONS.DATA_VIEW_ALL,
    PERMISSIONS.ALERTS_VIEW,
    // Strictly read-only: no mutation actions permitted
  ],
}

/**
 * Checks whether a role has a specific permission
 * @param {string} role 
 * @param {string} permission 
 * @returns {boolean}
 */
function hasPermission(role, permission) {
  if (!role || !permission) return false
  const perms = ROLE_PERMISSIONS[role.toUpperCase()]
  if (!perms) return false
  return perms.includes(permission)
}

/**
 * Returns all permissions for a role
 * @param {string} role 
 * @returns {string[]}
 */
function getRolePermissions(role) {
  if (!role) return []
  return ROLE_PERMISSIONS[role.toUpperCase()] || []
}

module.exports = {
  PERMISSIONS,
  ROLE_PERMISSIONS,
  hasPermission,
  getRolePermissions,
}
